language: java

jdk:
  - oraclejdk11

matrix:
  - jdk: oraclejdk11
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

addons:
  sonarcloud:
    organization: "smalaca-github"
    token: $SONAR_TOKEN

script:
  - mvn -Pstatic-analysis clean compile
  - mvn -Parchitecture-tests test
  - mvn -Pdomain-tests verify
  - mvn -Pintegration-tests verify
  - mvn -Psystem-tests verify
  - sonar-scanner